name: Trigger condition test

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - "trigger-test/**"

jobs:
  check-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Show trigger event
        run: echo "Triggered by ${{ github.event_name }}"